### ISSUE TITLE
get rquest error

### ISSUE THREAD

**Issue by can101** [DenizYanbollu/yokapi#1]
> server view
![Screenshot](https://user-images.githubusercontent.com/68447137/138089229-a08913fa-d618-437a-bbd1-3ef697b817af.png)

> Fetch or Axios get request view
>> Fetch
![image](https://user-images.githubusercontent.com/68447137/138089808-173a18e5-3ac4-43a8-80b2-303313dc074a.png
>> Axios
![Screenshot (1)](https://user-images.githubusercontent.com/68447137/138090948-119061cc-4b05-474d-a0ae-80d2d5ec7693.png)
)

**Comment by can101** [comment]
I don't use the client app  not working
maybe only to me

**Comment by DenizYanbollu** [comment]
Can you paste the code line that you're getting this error?

**Comment by can101** [comment]
**these  are seen**

> Converting circular structure to JSON --> starting at object with constructor 'ClientRequest' | property 'socket' -> object with constructor 'Socket' --- property '_httpMessage' closes the circle

> TypeError: Network request failed

thanks for everythings
